apiVersion: v1
kind: Service
metadata:
  name: {{ include "drone.fullname" . }}
  labels:
    {{- include "drone.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.http.type }}
  ports:
  {{- if .Values.service.https }}
    - port: {{ .Values.service.https.port }}
      targetPort: {{ .Values.service.https.targetPort }}
      protocol: TCP
      name: https
  {{- else -}}
    - port: {{ .Values.service.http.port }}
      targetPort: {{ .Values.service.http.targetPort }}
      protocol: TCP
      name: http
  {{- end }}
  selector:
    {{- include "drone.selectorLabels" . | nindent 4 }}
